name: Docs

on:
  pull_request:
    branches: ['main']
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -e '.[docs]'
    - name: Build docs
      run: |
        sphinx-build -W -b html docs docs/build/html