name: Format

on:
  pull_request:
      branches: ['main']
      types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install isort 'black[jupyter]' pylint ruff pylint qbraid-cli
      - name: Check isort, ruff, headers
        run: |
          ruff check qbraid_algorithms examples tests bin
          isort --check-only qbraid_algorithms tests bin
          black --check qbraid_algorithms tests bin examples --line-length 100
          pylint qbraid_algorithms tests bin examples --disable=W0108,W0511,W0401,R0902,E0401 --ignore=qbraid_algorithms/_version.py
          qbraid admin headers qbraid_algorithms tests bin --type gpl