name: Pre-release to PyPI

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Build pre-release dist & upload to PyPI
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: python -m pip install -U pip wheel build toml-cli qbraid-core

      - name: Build binary wheel + source tarball
        id: build-dev
        run: |
            export PRE_RELEASE_VERSION=$(python tools/stamp_pre_release.py)
            [[ "$PRE_RELEASE_VERSION" =~ .*(-a\.|-b\.|-rc\.).* ]] && echo "Deploying pre-release version '$PRE_RELEASE_VERSION'" || (echo "not pre-release version"; exit 0)
            out_dir="${PWD}/dist"
            bin/create_dev_build.sh $PRE_RELEASE_VERSION "${out_dir}"
            echo "dir=$out_dir" >> $GITHUB_OUTPUT

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}